<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>
		<!--vai para a rota de deslogar-->
	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>
				<!--valores recuperados pelo metodo recuperaInfoPerfil do app controller-->
				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->info_usuario['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">
						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_tweets['qt_tweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_seguindo['qt_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_seguidores['qt_seguidores']?></span>
						</div>
					</div>
				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<!--vai para a rota quem_seguir mandando o dado escrito no input via get-->
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input name="pesquisa" type="text" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<!--para cada usuario recuperado pelo metodo getAll da classe usuario chamado pelo metodo quemseguir de app controller...-->
			<?php foreach($this->view->usuarios as $ind => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<!--exibe o nome dos usuarios que o usuario da sessao pesquisou a opção de seguir caso nao siga
									 ou deixar de seguir caso ja siga-->
									<div class="col-md-6">
										<?= $usuario['nome'] ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<!--vai para a rota acao-->
											<?php if($usuario['seguindo_sn']==0){?>
												<a href="/acao?acao=seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-success">Seguir</a>
											<?php }?>
											<?php if($usuario['seguindo_sn']==1){?>
												<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-danger">Deixar de seguir</a>
											<?php }?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>