<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>
		<!--vai para a rota de deslogar-->
	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">	
		<div class="col-md-3">
			<div class="perfil">
				<div class="perfilTopo">

				</div>
				<!--valores recuperados pelo metodo recuperaInfoPerfil do app controller-->
				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->info_usuario['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">
						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_tweets['qt_tweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_seguindo['qt_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->qt_seguidores['qt_seguidores']?></span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<!--vai para a rota tweet enviando dados via post-->
					<form action="/tweet" method="post">
						<textarea name='tweet' class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!--para cada tweet recuperado pelo metodo getAll da classe tweet, chamado pelo metodo timeline da classe appcontroller
			e atribuido a variavel tweets, criada dinamicamente...-->
			<?php foreach($this->view->tweets as $id => $texto){ ?>
				<div class="row tweet">
					<div class="col">
						<!--mostra os dados do tweet-->
						<p><strong><?=$texto['nome']?></strong> <small><span class="text text-muted">- <?=$texto['data']?></span></small></p>
						<p><?=$texto['tweet']?></p>

						<br />
						<form>
							<div class="col d-flex justify-content-end">
								<!--se o id_usuario do tweet for o id do usuario da sessao, ou seja ele que fez o tweet,
								a opcao de remover o tweet é mostrada-->
								<?php if($texto['id_usuario']==$_SESSION['id']){?>
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								<?php }?>	
							</div>
						</form>		
					</div>
				</div>
			<?php } ?>
		</div>

		<div class="col-md-3">
			<div class="quemSeguir pt-1">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<!--vai para a rota quem_seguir-->
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>
	</div>
</div>